server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1

            - id: transport-service
              uri: http://localhost:8082
              predicates:
                - Path=/transport-service/**
              filters:
                - StripPrefix=1

            - id: rental-service
              uri: http://localhost:8083
              predicates:
                - Path=/rental-service/**
              filters:
                - StripPrefix=1

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: transport-service
        url: /transport-service/v3/api-docs
      - name: rental-service
        url: /rental-service/v3/api-docs