spring:
  application:
    name: scoooting

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/scoooting
    username: postgres
    password: postgres_pass

  flyway:
    baseline-on-migrate: true
    placeholders:
      adminUsername: admin
      adminEmail: admin@ya.ru
      adminPassword: 1234