spring:
  application:
    name: scoooting
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scoooting
    username: postgres
    password: ma826330

  flyway:
    baseline-on-migrate: true
    placeholders:
      adminUsername: admin
      adminEmail: admin@ya.ru
      adminPassword: 1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true