server:
  port: 8082

spring:
  application:
    name: transport-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: true