server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Scoooting/Configs.git
          username: ${CONFIG_USERNAME}
          password: ${CONFIG_TOKEN}
          default-label: main
          search-paths: "{application}"